layout_spectrum: 0.4373719
typography_spectrum: 0.8444353
color:
  saturation: 0.9724933
  lightness: 0.2082945
  brandStrength: 0.1818203
  rhythmicContrast: 0.4767922
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: bunncoffeeandtea
